title: "Fault Tolerance on OCI"
description: "Fault tolerant service that provides compute instance, local filesystem, HTTP and DNS with synchronous stateful replication and 10 seconds switchover"

schemaVersion: 1.1.0

locale: "en"

variableGroups:

  - title: "Enable Cross-AD Mode"
    variables:
      - cross_ad_fault_tolerance

  - title: "Region"
    visible: false
    variables:
      - region

  - title: "Region Selection"
    required: true
    visible:
      not:
        - cross_ad_fault_tolerance
    variables:
      - region_single_ad

  - title: "Region Selection"
    required: true
    visible: cross_ad_fault_tolerance
    variables:
      - region_multi_ad

  - title: "Location"
    variables:
      - tenancy_ocid
      - compartment_ocid
      - vcn_ocid
      - subnet_ocid

  - title: "Fault Tolerant Compute Instance"
    variables:
      - shape
      - ocpus
      - memory_gbs

  - title: "Fault Tolerant Storage"
    variables:
      - block_volume_size_gbs
      - fs_type
      - mount_point

  - title: "User Endpoints"
    variables:
      - service_hostname
      - ssh_public_key

variables:

  cross_ad_fault_tolerance:
    title: "Place standby resource in different Availability Domain"
    type: boolean
    default: false

  region_single_ad:
    required: true
    type: enum
    title: OCI Region (All Regions)
    description: All public regions
    enum:
      - af-johannesburg-1
      - ap-batam-1
      - ap-chuncheon-1
      - ap-hyderabad-1
      - ap-melbourne-1
      - ap-mumbai-1
      - ap-osaka-1
      - ap-seoul-1
      - ap-singapore-1
      - ap-singapore-2
      - ap-sydney-1
      - ap-tokyo-1
      - ca-montreal-1
      - ca-toronto-1
      - eu-amsterdam-1
      - eu-jovanovac-1
      - eu-madrid-1
      - eu-madrid-3
      - eu-marseille-1
      - eu-milan-1
      - eu-paris-1
      - eu-stockholm-1
      - eu-turin-1
      - eu-zurich-1
      - il-jerusalem-1
      - me-abudhabi-1
      - me-dubai-1
      - me-jeddah-1
      - me-riyadh-1
      - mx-monterrey-1
      - mx-queretaro-1
      - sa-bogota-1
      - sa-santiago-1
      - sa-saopaulo-1
      - sa-valparaiso-1
      - sa-vinhedo-1
      - uk-cardiff-1
      - us-sanjose-1
      - eu-frankfurt-1
      - uk-london-1
      - us-ashburn-1
      - us-phoenix-1
      - us-chicago-1
    default: me-dubai-1

  region_multi_ad:
    required: true
    type: enum
    title: OCI Region (Multi-AD only)
    enum:
      - eu-frankfurt-1
      - uk-london-1
      - us-ashburn-1
      - us-phoenix-1
      - us-chicago-1
    default: eu-frankfurt-1

  tenancy_ocid:
    title: "Tenancy"
    description: "OCI tenancy OCID where the service will be deployed"

  compartment_ocid:
    title: "Compartment"
    description: "OCI compartment OCID where the service will be deployed"

  vcn_ocid:
    title: "VCN"
    description: "Virtual Cloud Network OCID where the service will be deployed"

  subnet_ocid:
    title: "Subnet"
    description: "Subnet OCID where the service will be deployed"

  shape:
    title: "Compute Shape"
    description: "OCI compute shape for fault-tolerant instance"
    type: enum
    enum:
      - VM.Standard.E5.Flex
      - VM.Standard.E4.Flex
      - VM.Standard3.Flex
    default: VM.Standard.E5.Flex

  ocpus:
    title: "OCPUs"

  memory_gbs:
    title: "Memory (GB)"

  block_volume_size_gbs:
    title: "Raw Size (GB)"

  fs_type:
    title: "Filesystem"
    description: "Filesystem for fault-tolerant storage"
    type: enum
    enum:
      - xfs
      - ext4
    default: xfs

  mount_point:
    title: "Mount Point"

  service_hostname:
    title: "HTTP Endpoint Name"

  ssh_public_key:
    title: "Public Key for External SSH Access"
